### PR TITLE
Control if a command is enabled, added truncation to areas

### PR DESCRIPTION
**Pull request by UpsetDavid**
Added a new file (commands.js) - that has a list of all commands. 
These have a true/false value. 

When a message is received, and confirmed to be a command, we check if the command (in commands.js) has a value of true in order to continue.

I also added a simple truncation to hawku.js that will ensure that if the area is ~52.4444445, it will truncate it to 52.44 (it will not round up or down).

### CODE REVIEW

**Comment by UpsetDavid** [comment]
I left my current commands.js as it is for an example of how I have it configured. 

These can also be consolidated into config.js if desired - I debated this for simplicity and naming sake, but I wasn't sure of the preferred naming scheme you wanted for this file since it could look almost the same as the configuration lines.

**Comment by travisbartholome** [comment]
I'm not sure I like the idea of having to maintain another separate list of commands like this. Also, with your current implementation, everything is sort of "off by default" if the user doesn't remember to specify it in their commands file (which I suspect I'll forget to do at some point).

How about instead we remove `commands.js` and add a config field `disabledCommands = ['commandName1', 'commandName2', 'etc']`, then do `if (config.disabledCommands.includes(msg)) { return; }` in index.js?

**Comment by travisbartholome** [comment]
Also, a couple of housekeeping things - your fork is out of date with the master branch history on this repo, because I squashed your previous PR into one commit (instead of like 15 small ones). For various reasons, this one among them, you probably don't ever want to commit stuff to the master branch of your fork directly - instead, make a branch and make the PR from that branch into master on this repo. That way whenever you sync your fork you'll always get a reasonable state on master (and should be able to fast-forward with no merge commit). If you want a reference, [this old-ish guide](https://code.tutsplus.com/tutorials/how-to-collaborate-on-github--net-34267) describes the typical workflow really well. See also [Github docs on syncing forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork).

To fix this I'd suggest running (in your repo):
```bash
# Just in case you haven't done these two already - it looks like you have, though
git remote add upstream https://github.com/travisbartholome/travisbot.git
git fetch upstream

# Fixing the issue
# Stash your new changes for this PR
git reset HEAD~2 --soft
git stash
# Hard reset to the last shared commit
git reset --hard 67470e0aa21cd3937a83dff6f990d70ab115d2d7
# Pull history from my repo
git merge upstream/master
# Overwrite the master history on your repo so that it matches mine
git push -f origin master
# Make a new branch called "disable-commands" for this new feature
git checkout -b disable-commands
# Replay your changes onto this new branch
git stash pop
# Go resolve the conflict in src/index.js in your editor (accept incoming change)
# Then, once you've done that:
git reset HEAD ./config.example.js
git checkout -- ./config.example.js # I don't know why this gets changed but it shouldn't
git add .
git commit -m "Your new commit message"
git push -u origin disable-commands
```

If there's a better way, I'm not sure what it is.

Also, as a second point, could you go check CONTRIBUTING.md for instructions on setting up the linter? There are some problems here that linting would clear up easily. VS Code has a good ESLint extension that you can configure to format on save (`dbaeumer.vscode-eslint`).

**Comment by travisbartholome** [comment]
You may need to make a new PR after doing all of that history editing above. It's probably easier if you just make a new one instead of trying to somehow massage this one into being correct.

**Comment by UpsetDavid** [comment]
closing, will be re-creating my own fork and making new branch and will submit new ones when these are addressed

**Pull request closed without merging**
